# Use the official Python 3.11 image from the Docker Hub
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file into the working directory
COPY ./requirements.txt .

# Install dependencies
RUN pip install --upgrade pip \
    && pip install -r requirements.txt

# Copy the rest of the application code into the working directory
COPY . .

RUN python -m grpc_tools.protoc -I . --python_out=. --grpc_python_out=. ./streaming.proto


EXPOSE 50051

# Command to run the application
# Modify this according to your application's entry point
CMD ["python", "server.py"]
