/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.12.4
// source: streaming.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = require('./streaming_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.StreamingServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.StreamingServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.StreamRequest,
 *   !proto.StreamResponse>}
 */
const methodDescriptor_StreamingService_StreamData = new grpc.web.MethodDescriptor(
  '/StreamingService/StreamData',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.StreamRequest,
  proto.StreamResponse,
  /**
   * @param {!proto.StreamRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.StreamResponse.deserializeBinary
);


/**
 * @param {!proto.StreamRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.StreamResponse>}
 *     The XHR Node Readable Stream
 */
proto.StreamingServiceClient.prototype.streamData =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/StreamingService/StreamData',
      request,
      metadata || {},
      methodDescriptor_StreamingService_StreamData);
};


/**
 * @param {!proto.StreamRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.StreamResponse>}
 *     The XHR Node Readable Stream
 */
proto.StreamingServicePromiseClient.prototype.streamData =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/StreamingService/StreamData',
      request,
      metadata || {},
      methodDescriptor_StreamingService_StreamData);
};


module.exports = proto;

